spring:
  profiles:
    active: local # default
    group:  # 실행될때 같이 실행될 파일들 선언!
      local:
        - common
      prod:
        - common


# 파일을 나누지않고 구분자로도 나눌수 있음
---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}   #인텔리제이 환경변수에서 설정해줬음





---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:7413/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME} #인텔리제이 환경변수에서 설정해줬음
    password: ${SPRING_DATASOURCE_PASSWORD} #인텔리제이 환경변수에서 설정해줬음
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    #      ddl-auto: create #create는 로컬 환경에서만 사용해야함 entity를 참조해서 스키마를 생성함 기존 테이블이 있으면 그것을 drop하고 생성하기때문에
    show-sql: true

pharmacy:
  recommendation:
    base:
      url: http://localhost:8080/dir/



---
spring:
  config:
    activate:
      on-profile: prod